-- Saídas do mês (o que é pago fora da gaveta), fornecedores, regime tributário e organização do estoque.

CREATE TABLE fornecedor (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(100) NOT NULL UNIQUE,
    fornece     VARCHAR(100),                 -- "bebidas", "frango", "embalagens"...
    telefone    VARCHAR(20),
    documento   VARCHAR(20),                  -- CNPJ, quando tiver
    observacao  VARCHAR(255),
    ativo       BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Pagamentos feitos por fora do caixa: PIX da conta, boleto, cartão, DAS do MEI, salário...
-- (o que sai da gaveta continua em caixa_movimento; o relatório do mês junta os dois)
CREATE TABLE saida (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data             DATE          NOT NULL,
    categoria        VARCHAR(20)   NOT NULL,
    descricao        VARCHAR(150)  NOT NULL,
    valor            NUMERIC(10,2) NOT NULL CHECK (valor > 0),
    forma            VARCHAR(20)   NOT NULL,
    fornecedor_id    BIGINT REFERENCES fornecedor(id),
    colaborador_id   BIGINT REFERENCES colaborador(id),
    despesa_fixa_id  BIGINT REFERENCES despesa_fixa(id) ON DELETE SET NULL,
    criado_em        TIMESTAMP WITH TIME ZONE NOT NULL,
    criado_por       VARCHAR(50)   NOT NULL
);
CREATE INDEX idx_saida_data ON saida (data);

ALTER TABLE caixa_movimento ADD COLUMN fornecedor_id BIGINT REFERENCES fornecedor(id);
CREATE INDEX idx_caixa_movimento_criado ON caixa_movimento (criado_em);
UPDATE caixa_movimento SET categoria = 'INSUMOS' WHERE categoria = 'FORNECEDOR';

-- MEI hoje; quando virar ME, troca aqui. O limite é configurável porque a lei muda.
ALTER TABLE configuracao_financeira ADD COLUMN regime_tributario VARCHAR(10) DEFAULT 'MEI' NOT NULL;
ALTER TABLE configuracao_financeira ADD COLUMN limite_faturamento_anual NUMERIC(12,2) DEFAULT 81000.00 NOT NULL;

-- Organização do estoque: "Refrigerantes" / "Coca-Cola" / "Coca-Cola Zero 2 L"
ALTER TABLE insumo ADD COLUMN grupo VARCHAR(40);
ALTER TABLE insumo ADD COLUMN marca VARCHAR(50);

CREATE INDEX idx_mov_tipo_data ON movimentacao_estoque (tipo, criado_em);
