-- Entrega grátis e entrega feita pelo dono, promoções com brinde e contas de valor variável.

-- taxa_entrega = quanto a entrega vale para o motoboy (taxa do bairro);
-- taxa_cobrada = quanto o cliente pagou de taxa (zero na entrega grátis).
ALTER TABLE pedido ADD COLUMN taxa_cobrada NUMERIC(10,2);
UPDATE pedido SET taxa_cobrada = taxa_entrega WHERE taxa_entrega IS NOT NULL;
-- Dono entregou: não tem motoboy para pagar e a taxa cobrada fica com a loja.
ALTER TABLE pedido ADD COLUMN entrega_pelo_dono BOOLEAN DEFAULT FALSE NOT NULL;

-- Dias da semana com entrega grátis, ex.: "TUESDAY,WEDNESDAY"
ALTER TABLE configuracao_loja ADD COLUMN dias_entrega_gratis VARCHAR(80);

-- "Comprou o Combo Especial, ganha um refrigerante 2 L" nos dias escolhidos.
CREATE TABLE promocao (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR(100) NOT NULL,
    produto_compra_id   BIGINT       NOT NULL REFERENCES produto(id),
    quantidade_compra   INTEGER      NOT NULL CHECK (quantidade_compra > 0),
    produto_brinde_id   BIGINT       NOT NULL REFERENCES produto(id),
    quantidade_brinde   INTEGER      NOT NULL CHECK (quantidade_brinde > 0),
    dias_semana         VARCHAR(80)  NOT NULL,
    ativa               BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Brinde entra no pedido com preço zero: sai do estoque e o custo pesa no lucro.
ALTER TABLE pedido_item ADD COLUMN brinde BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE pedido_item ADD COLUMN promocao VARCHAR(100);

-- Água e luz mudam todo mês: o valor de referência acompanha o último pagamento.
ALTER TABLE despesa_fixa ADD COLUMN valor_variavel BOOLEAN DEFAULT FALSE NOT NULL;
-- Linha digitável / código de barras da conta paga (comprovante para o contador)
ALTER TABLE saida ADD COLUMN codigo_barras VARCHAR(48);
