-- Notas fiscais de compra (NF-e) importadas pelo XML: dão entrada no estoque e viram uma saída.

CREATE TABLE nota_fiscal_compra (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave          VARCHAR(44)   NOT NULL UNIQUE,      -- impede importar a mesma nota duas vezes
    numero         VARCHAR(9)    NOT NULL,
    serie          VARCHAR(3)    NOT NULL,
    emitente_cnpj  VARCHAR(14)   NOT NULL,
    emitente_nome  VARCHAR(150)  NOT NULL,
    emitida_em     TIMESTAMP WITH TIME ZONE NOT NULL,
    valor_total    NUMERIC(12,2) NOT NULL,
    fornecedor_id  BIGINT REFERENCES fornecedor(id),
    importada_em   TIMESTAMP WITH TIME ZONE NOT NULL,
    importada_por  VARCHAR(50)   NOT NULL
);

-- "O código 12345 da Assaí é o insumo Coca-Cola 2 L, 6 unidades por item": lembrado para a próxima nota.
CREATE TABLE item_fornecedor (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id   BIGINT        NOT NULL REFERENCES fornecedor(id),
    codigo_produto  VARCHAR(60)   NOT NULL,
    descricao       VARCHAR(150)  NOT NULL,
    insumo_id       BIGINT        NOT NULL REFERENCES insumo(id),
    fator           NUMERIC(14,6) NOT NULL CHECK (fator > 0),
    CONSTRAINT uk_item_fornecedor UNIQUE (fornecedor_id, codigo_produto)
);
