-- Schema inicial do Point do Frango.
-- Compatível com PostgreSQL (Supabase) e H2 em modo PostgreSQL (dev/testes).
-- Valores em dinheiro: NUMERIC (nunca float/double). Custo por grama precisa de 6 casas.

CREATE TABLE usuario (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(100) NOT NULL,
    username    VARCHAR(50)  NOT NULL UNIQUE,
    senha_hash  VARCHAR(100) NOT NULL,
    perfil      VARCHAR(20)  NOT NULL,
    ativo       BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em   TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Matéria-prima comprada: frango, batata, óleo, embalagem...
CREATE TABLE insumo (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(100)   NOT NULL UNIQUE,
    unidade         VARCHAR(20)    NOT NULL,
    estoque_atual   NUMERIC(14,3)  NOT NULL DEFAULT 0,
    estoque_minimo  NUMERIC(14,3)  NOT NULL DEFAULT 0,
    custo_unitario  NUMERIC(14,6)  NOT NULL DEFAULT 0,
    ativo           BOOLEAN        NOT NULL DEFAULT TRUE,
    versao          BIGINT         NOT NULL DEFAULT 0
);

-- Item do cardápio: porção de isca, batata, anel de cebola, espetinho...
CREATE TABLE produto (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR(100)  NOT NULL UNIQUE,
    descricao    VARCHAR(255),
    categoria    VARCHAR(20)   NOT NULL,
    preco_venda  NUMERIC(10,2) NOT NULL,
    ativo        BOOLEAN       NOT NULL DEFAULT TRUE
);

-- Ficha técnica: quanto de cada insumo uma unidade do produto consome.
CREATE TABLE ficha_tecnica_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id  BIGINT        NOT NULL REFERENCES produto(id) ON DELETE CASCADE,
    insumo_id   BIGINT        NOT NULL REFERENCES insumo(id),
    quantidade  NUMERIC(14,3) NOT NULL CHECK (quantidade > 0),
    CONSTRAINT uk_ficha_produto_insumo UNIQUE (produto_id, insumo_id)
);

CREATE TABLE pedido (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canal               VARCHAR(20)   NOT NULL,
    status              VARCHAR(20)   NOT NULL,
    forma_pagamento     VARCHAR(20)   NOT NULL,
    cliente_nome        VARCHAR(100),
    cliente_telefone    VARCHAR(30),
    endereco_entrega    VARCHAR(255),
    observacao          VARCHAR(255),
    valor_total         NUMERIC(10,2) NOT NULL,
    -- "Potes" do rateio, congelados no momento da venda
    taxa_pagamento      NUMERIC(10,2) NOT NULL,
    reposicao_estoque   NUMERIC(10,2) NOT NULL,
    contas_fixas        NUMERIC(10,2) NOT NULL,
    lucro_liquido       NUMERIC(10,2) NOT NULL,
    pro_labore          NUMERIC(10,2) NOT NULL,
    reserva_emergencia  NUMERIC(10,2) NOT NULL,
    criado_por          VARCHAR(50),
    criado_em           TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em       TIMESTAMP WITH TIME ZONE NOT NULL,
    motivo_cancelamento VARCHAR(255)
);
CREATE INDEX idx_pedido_criado_em ON pedido (criado_em);
CREATE INDEX idx_pedido_status ON pedido (status);

-- Item do pedido guarda preço e custo do momento da venda (snapshot):
-- mudar o preço amanhã não reescreve o faturamento de hoje.
CREATE TABLE pedido_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id       BIGINT        NOT NULL REFERENCES pedido(id) ON DELETE CASCADE,
    produto_id      BIGINT        NOT NULL REFERENCES produto(id),
    nome_produto    VARCHAR(100)  NOT NULL,
    quantidade      INTEGER       NOT NULL CHECK (quantidade > 0),
    preco_unitario  NUMERIC(10,2) NOT NULL,
    custo_unitario  NUMERIC(14,6) NOT NULL
);
CREATE INDEX idx_pedido_item_pedido ON pedido_item (pedido_id);

-- Extrato do estoque: toda entrada, baixa, ajuste e estorno fica registrada.
CREATE TABLE movimentacao_estoque (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insumo_id         BIGINT        NOT NULL REFERENCES insumo(id),
    tipo              VARCHAR(20)   NOT NULL,
    quantidade        NUMERIC(14,3) NOT NULL,
    saldo_apos        NUMERIC(14,3) NOT NULL,
    custo_unitario    NUMERIC(14,6) NOT NULL,
    pedido_id         BIGINT        REFERENCES pedido(id),
    observacao        VARCHAR(255),
    usuario           VARCHAR(50),
    criado_em         TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_mov_insumo ON movimentacao_estoque (insumo_id, criado_em);
CREATE INDEX idx_mov_pedido ON movimentacao_estoque (pedido_id);

-- Linha única com os percentuais do rateio.
CREATE TABLE configuracao_financeira (
    id                       BIGINT PRIMARY KEY,
    percentual_contas_fixas  NUMERIC(5,2) NOT NULL,
    percentual_pro_labore    NUMERIC(5,2) NOT NULL,
    taxa_pix                 NUMERIC(5,2) NOT NULL,
    taxa_debito              NUMERIC(5,2) NOT NULL,
    taxa_credito             NUMERIC(5,2) NOT NULL,
    atualizado_em            TIMESTAMP WITH TIME ZONE NOT NULL
);
INSERT INTO configuracao_financeira
    (id, percentual_contas_fixas, percentual_pro_labore, taxa_pix, taxa_debito, taxa_credito, atualizado_em)
VALUES (1, 20.00, 80.00, 0.00, 1.99, 4.98, CURRENT_TIMESTAMP);

-- Contas do mês: aluguel, luz, água, internet, contador...
CREATE TABLE despesa_fixa (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao       VARCHAR(100)  NOT NULL,
    valor_mensal    NUMERIC(10,2) NOT NULL CHECK (valor_mensal >= 0),
    dia_vencimento  INTEGER       CHECK (dia_vencimento BETWEEN 1 AND 31),
    ativa           BOOLEAN       NOT NULL DEFAULT TRUE
);
