-- Embalagens de compra, unidade de uso (ex.: "isca") e modos de informar a ficha técnica.
--
-- Precisão: 1 isca = 1/12 kg = 0,0833333333 kg. Com 3 casas, 12 iscas baixariam 0,996 kg
-- em vez de 1 kg. Por isso o estoque passa a ter 6 casas e a ficha técnica 10.

ALTER TABLE insumo               ALTER COLUMN estoque_atual  SET DATA TYPE NUMERIC(16,6);
ALTER TABLE insumo               ALTER COLUMN estoque_minimo SET DATA TYPE NUMERIC(16,6);
ALTER TABLE movimentacao_estoque ALTER COLUMN quantidade     SET DATA TYPE NUMERIC(16,6);
ALTER TABLE movimentacao_estoque ALTER COLUMN saldo_apos     SET DATA TYPE NUMERIC(16,6);
ALTER TABLE ficha_tecnica_item   ALTER COLUMN quantidade     SET DATA TYPE NUMERIC(20,10);

-- Unidade de uso: como o insumo é contado na cozinha. Ex.: isca de frango → "isca", 12 por kg.
ALTER TABLE insumo ADD COLUMN unidade_uso_nome        VARCHAR(30);
ALTER TABLE insumo ADD COLUMN unidade_uso_por_unidade NUMERIC(14,6);

-- Como o insumo chega do fornecedor. Ex.: batata → "Saco 2 kg" (conteúdo 2,000 kg).
CREATE TABLE insumo_embalagem (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insumo_id  BIGINT        NOT NULL REFERENCES insumo(id) ON DELETE CASCADE,
    nome       VARCHAR(50)   NOT NULL,
    conteudo   NUMERIC(14,6) NOT NULL CHECK (conteudo > 0),
    CONSTRAINT uk_embalagem_insumo_nome UNIQUE (insumo_id, nome)
);

-- Ficha técnica: guarda o que a pessoa digitou (modo + quantidade informada) e a
-- quantidade convertida para a unidade do insumo (coluna "quantidade", usada na baixa).
ALTER TABLE ficha_tecnica_item ADD COLUMN modo VARCHAR(30) DEFAULT 'UNIDADE_BASE' NOT NULL;
ALTER TABLE ficha_tecnica_item ADD COLUMN quantidade_informada NUMERIC(16,6);
ALTER TABLE ficha_tecnica_item ADD COLUMN embalagem_id BIGINT REFERENCES insumo_embalagem(id);
UPDATE ficha_tecnica_item SET quantidade_informada = quantidade;
ALTER TABLE ficha_tecnica_item ALTER COLUMN quantidade_informada SET NOT NULL;
