-- Comandas (mesa/cliente consumindo no local): vários pedidos ao longo do tempo,
-- pagamento só no fechamento, com taxa de serviço opcional.

CREATE TABLE comanda (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificacao        VARCHAR(50)   NOT NULL,          -- "Mesa 4", "João", "Balcão 2"
    status               VARCHAR(20)   NOT NULL,
    observacao           VARCHAR(255),
    aberta_por           VARCHAR(50),
    aberta_em            TIMESTAMP WITH TIME ZONE NOT NULL,
    fechada_por          VARCHAR(50),
    fechada_em           TIMESTAMP WITH TIME ZONE,
    forma_pagamento      VARCHAR(20),
    percentual_servico   NUMERIC(5,2),
    cobrar_servico       BOOLEAN,
    valor_itens          NUMERIC(10,2),
    valor_servico        NUMERIC(10,2),
    valor_total          NUMERIC(10,2),
    motivo_cancelamento  VARCHAR(255),
    versao               BIGINT        NOT NULL DEFAULT 0
);
CREATE INDEX idx_comanda_status ON comanda (status);
CREATE INDEX idx_comanda_fechada_em ON comanda (fechada_em);

-- Pedido pode pertencer a uma comanda. Nesse caso a forma de pagamento só é conhecida
-- no fechamento, então a coluna passa a aceitar nulo ("a receber").
ALTER TABLE pedido ADD COLUMN comanda_id BIGINT REFERENCES comanda(id);
ALTER TABLE pedido ALTER COLUMN forma_pagamento DROP NOT NULL;
CREATE INDEX idx_pedido_comanda ON pedido (comanda_id);

-- Dados que saem no cupom + taxa de serviço. Linha única (id = 1).
CREATE TABLE configuracao_loja (
    id                    BIGINT PRIMARY KEY,
    nome                  VARCHAR(100) NOT NULL,
    documento             VARCHAR(30),
    endereco              VARCHAR(200),
    telefone              VARCHAR(30),
    mensagem_rodape       VARCHAR(200),
    percentual_servico    NUMERIC(5,2) NOT NULL,
    servico_marcado       BOOLEAN      NOT NULL,
    atualizado_em         TIMESTAMP WITH TIME ZONE NOT NULL
);
INSERT INTO configuracao_loja (id, nome, documento, endereco, telefone, mensagem_rodape,
                               percentual_servico, servico_marcado, atualizado_em)
VALUES (1, 'Point do Frango', NULL, NULL, NULL, 'Obrigado pela preferência!', 10.00, TRUE, CURRENT_TIMESTAMP);
