-- Entregas por bairro, clientes do WhatsApp, equipe (motoboy/funcionário), caixa do dia e troco.

CREATE TABLE bairro (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(80)   NOT NULL UNIQUE,
    taxa_entrega  NUMERIC(10,2) NOT NULL CHECK (taxa_entrega >= 0),
    ativo         BOOLEAN       NOT NULL DEFAULT TRUE
);

-- Só o necessário para entregar (LGPD: minimização). Telefone guardado só com dígitos.
CREATE TABLE cliente (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR(100) NOT NULL,
    telefone          VARCHAR(15)  NOT NULL UNIQUE,
    endereco          VARCHAR(200),
    referencia        VARCHAR(150),
    bairro_id         BIGINT REFERENCES bairro(id),
    criado_em         TIMESTAMP WITH TIME ZONE NOT NULL,
    ultimo_pedido_em  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_cliente_ultimo_pedido ON cliente (ultimo_pedido_em);

CREATE TABLE colaborador (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(100)  NOT NULL,
    funcao        VARCHAR(20)   NOT NULL,
    valor_diaria  NUMERIC(10,2) NOT NULL CHECK (valor_diaria >= 0),
    ativo         BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE TABLE caixa (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status             VARCHAR(20)   NOT NULL,
    aberto_em          TIMESTAMP WITH TIME ZONE NOT NULL,
    aberto_por         VARCHAR(50)   NOT NULL,
    valor_abertura     NUMERIC(10,2) NOT NULL CHECK (valor_abertura >= 0),
    fechado_em         TIMESTAMP WITH TIME ZONE,
    fechado_por        VARCHAR(50),
    dinheiro_esperado  NUMERIC(10,2),
    dinheiro_contado   NUMERIC(10,2),
    observacao         VARCHAR(255),
    versao             BIGINT        NOT NULL DEFAULT 0
);
CREATE INDEX idx_caixa_status ON caixa (status);

-- Saídas (diária, motoboy, compra no mercado...) e suprimentos (dinheiro colocado na gaveta).
CREATE TABLE caixa_movimento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caixa_id        BIGINT        NOT NULL REFERENCES caixa(id),
    tipo            VARCHAR(20)   NOT NULL,
    categoria       VARCHAR(20)   NOT NULL,
    descricao       VARCHAR(150)  NOT NULL,
    valor           NUMERIC(10,2) NOT NULL CHECK (valor > 0),
    forma           VARCHAR(20)   NOT NULL,
    colaborador_id  BIGINT REFERENCES colaborador(id),
    inclui_diaria   BOOLEAN       NOT NULL DEFAULT FALSE,
    criado_em       TIMESTAMP WITH TIME ZONE NOT NULL,
    criado_por      VARCHAR(50)   NOT NULL
);
CREATE INDEX idx_caixa_movimento_caixa ON caixa_movimento (caixa_id);

-- Entrega: a taxa é do motoboy, por isso fica fora de valor_total (que alimenta o rateio).
ALTER TABLE pedido ADD COLUMN cliente_id           BIGINT REFERENCES cliente(id);
ALTER TABLE pedido ADD COLUMN bairro_entrega       VARCHAR(80);
ALTER TABLE pedido ADD COLUMN taxa_entrega         NUMERIC(10,2);
ALTER TABLE pedido ADD COLUMN entregador_id        BIGINT REFERENCES colaborador(id);
ALTER TABLE pedido ADD COLUMN acerto_entregador_id BIGINT REFERENCES caixa_movimento(id);
ALTER TABLE pedido ADD COLUMN valor_recebido       NUMERIC(10,2);
CREATE INDEX idx_pedido_entregador ON pedido (entregador_id, acerto_entregador_id);
CREATE INDEX idx_pedido_cliente ON pedido (cliente_id);

ALTER TABLE comanda ADD COLUMN valor_recebido NUMERIC(10,2);

-- Nomes personalizados do menu lateral, em JSON: {"pdv":"Caixa rápido", ...}
ALTER TABLE configuracao_loja ADD COLUMN nomes_menu VARCHAR(1000);
